#! /bin/sh

# Autostarting sxhkd, and others
pgrep -x sxhkd > /dev/null || sxhkd &
picom &
nm-applet &
firewalld &
/usr/lib/polkit-kde-authentication-agent-1 &
$HOME/.config/polybar/launch.sh &
feh --bg-fill ~/Workspace/Arch_EXP/red-wallpapers/wall-1.png

# Workspaces
bspc monitor eDP-1 -d I II III IV V VI  

# Workspaces behavior and appearence
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config remove_disabled_monitors      true
bspc config remove_unplugged_monitors     true
bspc config merge_overlapping_monitors    true

# For starting a app on a certain desktop
bspc rule -a firefox desktop='^2'
bspc rule -a kitty desktop='^1'
