#! /bin/sh

# Autostarting sxhkd, and others
pgrep -x sxhkd > /dev/null || sxhkd &
picom &
feh --bg-fill --randomize ~/Workspace/Arch_EXP/red-wallpapers/* &
nm-applet &
#flameshot &
conky &
$HOME/.config/polybar/launch.sh 

# Workspaces
bspc monitor -d I II III IV V VI VII VIII IX X

# Workspaces behavior and appearence
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


# For starting a app on a certain desktop
bspc rule -a firefox desktop='^2'
bspc rule -a kitty desktop='^1'
