#! /bin/sh

# Autostarting sxhkd, and others
pgrep -x sxhkd > /dev/null || sxhkd &
picom &
nm-applet &
blueman-applet &
dunst &
pgrep -x firewall-applet > /dev/null || firewall-applet &
firewalld &
flameshot & 
xss-lock -- betterlockscreen -l &
/usr/lib/polkit-kde-authentication-agent-1 &
# $HOME/.config/polybar/launch.sh &
bash ~/.config/polybar/launch.sh --blocks
# polybar example &
feh --bg-fill ~/Workspace/Arch_EXP/wallpapers/vgirl.jpg

# Workspaces
bspc monitor eDP-1 -d 1 2 3 4  
bspc monitor HDMI-1 -d 5 6 7 8

# Workspaces behavior and appearence
bspc config border_width        2
bspc config window_gap          4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config remove_disabled_monitors      true
bspc config remove_unplugged_monitors     true
bspc config merge_overlapping_monitors    true

# For starting a app on a certain desktop
# bspc rule -a firefox desktop='^2'
# bspc rule -a kitty desktop='^1'
#bspc rule -a steam desktop='^4' follow=on state=floating
