require("aktsu.plugins-setup")
require("aktsu.core.options")
require("aktsu.core.theme")
require("aktsu.core.keymaps")
require("aktsu.plugins.lualine")
require("aktsu.plugins.nvim-tree")
require("aktsu.plugins.autopairs")
require("aktsu.plugins.colorizer")
require("aktsu.plugins.vimtex")

